run: python2 python3

python2:
	ipython nbconvert --to=html --ExecutePreprocessor.enabled=True test_notebook.ipynb
python3:
	ipython3 nbconvert --to=html --ExecutePreprocessor.enabled=True test_notebook.ipynb

.PHONY: run

