run: python2 python3

python2:	
	python basic_plotting_pyplot.py	
	python basic_plotting_tkagg_pyplot.py

python3:
	python3 basic_plotting_pyplot.py	
	python3 basic_plotting_tkagg_pyplot.py

.PHONY: run
