run: python2 python3

python2:
	python basic_plotting.py
	python basic_plotting_pyplot.py
	python basic_plotting_tkagg.py
	python basic_plotting_tkagg_pyplot.py

python3:
	python3 basic_plotting.py
	python3 basic_plotting_pyplot.py
	python3 basic_plotting_tkagg.py
	python3 basic_plotting_tkagg_pyplot.py

.PHONY: run
